url: http://oiworld.github.io
baseurl: /CarbonFootprintGoogleMaps

# Site Settings
title: Carbon Footprint for Maps
description: "A Google Chrome browser extension that displays carbon footprint information on multiple map services."
keywords: "chrome, plugin"
google-tracking-id:
author: "Chirag, Prateek, Kolya"

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE"]

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default"